# Generated by Django 4.1.5 on 2023-01-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnetdiags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='ipadress',
            field=models.GenericIPAddressField(default='192.168.32.47'),
        ),
    ]
