# Generated by Django 4.1.5 on 2023-01-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnetdiags', '0002_server_ipadress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField(auto_now_add=True)),
                ('log_ping_count', models.IntegerField()),
                ('log_lost_count', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='server',
            name='ipadress',
        ),
    ]
