# Generated by Django 4.1.5 on 2023-01-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnetdiags', '0003_log_remove_server_ipadress'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='log_host',
            field=models.CharField(default='host', max_length=40),
        ),
    ]
