# Generated by Django 4.1.5 on 2023-02-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnetdiags', '0007_log_log_ping_lost_log_log_ping_receive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='log_percent_lost',
            field=models.FloatField(default=0.0),
        ),
    ]
